name: Generate Snake animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main --follow-tags
